[package]
name = "lennard-jones"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.dev]
opt-level = 2

[dependencies]
rand = "0.8.4"
statrs = "0.16"
rayon = "1.5.1"
